spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

logging:
  level:
    root: warn
    com.xrq.mybatisplus.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
 global-config:
   db-config:
     id-type: AUTO
     logic-not-delete-value: 0  #字段值为0代表逻辑未删除
     logic-delete-value: 1      #字段值为1代表逻辑已删除
   #    table-prefix: mp_   设置表名字前缀
 mapper-locations:
    mapper/*           # xml存放路径
 #config-location: classpath:mybatis-config.xml
 type-aliases-package: com.xrq.mybatisplus.entity
 configuration:      # configuration和 config-location:不能同时出现，否则会报错
   map-underscore-to-camel-case: true #开启默认驼峰属性名和列名映射 ,mp默认就是true（mybatis默认是false）。