spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

logging:
  level:
    root: warn
    com.xrq.mybatisplus.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
 global-config:
   db-config:
     id-type: AUTO
 mapper-locations:
    mapper/*
 config-location: classpath:mybatis-config.xml
 type-aliases-package: com.xrq.mybatisplus.entity
# xml存放路径